import { Injectable } from '@angular/core';

@Injectable()
export class TaoisighService {
  public data: Array<{tid: number, name: string, image: string, party: any, dob: any, dod: any, ministries: any, electionDate: any, termStartDate: any, termEndDate: any, headsOfState: any, deputy: any, leadershipStartDate: any, leadershipEndDate: any, constituencies: any, placeOfBirth: string, placeOfDeath: string, buried: string, religion: string, numOfTermsServed: number, profile: string, firstElectedToParliament: any}> = [
    {
      tid: 0,
      name: "W.T. Cosgrave",
      image:'',
      party:["Sinn Fein", "Cumann na nGaedhael", "Fine Gael"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 1,
      name: "Eamon de Valera",
      image:'',
      party:["Sinn Fein", "Fianna Fail"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 2,
      name: "John A. Costello",
      image:'',
      party:["Cumann na nGaedhael", "Fine Gael"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 3,
      name: "Sean Lemass",
      image:'',
      party:["Fianna Fail"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 4,
      name: "Jack Lynch",
      image:'',
      party:["Fianna Fail"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 5,
      name: "Liam Cosgrave",
      image:'',
      party:["Fine Gael"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 6,
      name: "Charles Haughey",
      image:'',
      party:["Fianna Fail"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 7,
      name: "Garret FitzGerald",
      image:'',
      party:["Fine Gael"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 8,
      name: "Albert Reynolds",
      image:'',
      party:["Fianna Fail"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 9,
      name: "John Bruton",
      image:'',
      party:["Fine Gael"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 10,
      name: "Bertie Ahern",
      image:'',
      party:["Fianna Fail"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 11,
      name: "Brian Cowen",
      image:'',
      party:["Fianna Fail"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 12,
      name: "Enda Kenny",
      image:'',
      party:["Fine Gael"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
    {
      tid: 13,
      name: "Leo Varadkar",
      image:'',
      party:["Fine Gael"],
      dob: "06/06/1880",
      dod: "16/11/1965",
      ministries: ["Local Government"],
      electionDate: "N/A",
      termStartDate: "06/12/1922",
      termEndDate: "09/03/32",
      headsOfState: "George V",
      deputy: ["Kevin O'Higgins", "Ernest Blythe"],
      leadershipStartDate: "1922",
      leadershipEndDate: "1944",
      constituencies: ["Kilkenny City", "Kilkenny North", "Carlow Kilkenny", "Cork Borough"],
      placeOfBirth: "Dublin",
      placeOfDeath: "Dublin",
      buried: "Goldenbridge",
      religion: "Roman Catholic",
      numOfTermsServed: 2,
      profile: "",
      firstElectedToParliament: "1917"
    },
]
  constructor() { }

}
